### Créé livre Harry Potter
POST http://localhost:8080/api/livres
Content-Type: application/json

{
  "titre": "Harry Potter à l'école des sorciers",
  "auteur": "J.K. Rowling",
  "langue": "francais",
  "stock": 1,
  "genreIds": [],
  "buIds": [1]
}

### Créé livre Le petit prince
POST http://localhost:8080/api/livres
Content-Type: application/json

{
  "titre": "Le petit prince",
  "auteur": "Antoine de Saint Exuperi",
  "langue": "francais",
  "stock": 1,
  "genreIds": [],
  "buIds": [1]
}

### Test livre bien créé
GET http://localhost:8080/api/livres

### Test recherche par titre
GET http://localhost:8080/api/catalogue/filtre?titre=Harry
Accept: application/json

### Test recherche par auteur
GET http://localhost:8080/api/catalogue/filtre?auteur=Rowling
Accept: application/json

### Test recherche par genre
GET http://localhost:8080/api/catalogue/filtre?genre=Fantasy
Accept: application/json

### Test sans paramètre
GET http://localhost:8080/api/catalogue
Accept: application/json

### Test récuperation du catalogue
GET http://localhost:8080/api/catalogue/filtre