###Permet de récupérer les information de la BU dont l'id est en body
POST http://localhost:8080/api/bu
Accept: application/json
Content-Type: application/json

{
  "nom" : "test2"
}

###Permet de récupérer les information de la BU dont l'id est en body
GET http://localhost:8080/api/bu
Accept: application/json
Content-Type: application/json





###Permet de creer des information pour la BU dont l'id est en body
POST http://localhost:8080/api/info
Accept: application/json
Content-Type: application/json

{
  "informations": "Info",
  "nom": "nom",
  "idBu" : 1
}

###Permet de récupérer les information de la BU dont l'id est en body
GET http://localhost:8080/api/info?idBU=0
Accept: application/json
Content-Type: application/json


###Permet de récupérer les information de la BU dont l'id est en body
GET http://localhost:8080/api/info?idBU=1
Accept: application/json
Content-Type: application/json


