### Test Get Genre
GET http://localhost:8080/api/test/genre

### Test Post Genre
POST http://localhost:8080/api/test/genre


### Test Get Livre
GET http://localhost:8080/api/test/livre

### Test Post Livre
POST http://localhost:8080/api/test/livre


### Test Get InfoBU
GET http://localhost:8080/api/test/livre

### Test Post InfoBU
POST http://localhost:8080/api/test/livre

### Test Get BU
GET http://localhost:8080/api/test/livre

### Test Post BU
POST http://localhost:8080/api/test/livre



